packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  "@homebridge/node-pty-prebuilt-multiarch": true
  cpu-features: true
  esbuild: true
  protobufjs: true
  secp256k1: true
  ssh2: true
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "@gearbox-protocol/*"
